$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
display_name: ds-prod-train
experiment_name: ds-prod
code: .
command: python src/train.py
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240108.v1
compute: azureml:cpu-cluster
